steps:
  - name: 'sonarsource/sonar-scanner-cli'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        sonar-scanner \
          -Dsonar.projectKey=karanranams7_html-gcp-ci-cd \
          -Dsonar.organization=karanranams7 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$$SONAR_TOKEN
    secretEnv: ['SONAR_TOKEN']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/html-app:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/html-app:$SHORT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'html-app'
      - '--image=gcr.io/$PROJECT_ID/html-app:$SHORT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/SONAR_TOKEN/versions/latest
      env: 'SONAR_TOKEN'
